version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=street_artists_map
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080